routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){

        Route::get('/home', 'HomeController@index')->name('home');

        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::put('/profile', 'ProfileController@update')->name('profile.update');

        Route::get('/about', function () {
            return view('about');
        })->name('about');


        // Route::get('/', function () {
        //     return view('login');
        // });


        Route::resource('/product', 'ProductController')->middleware(['Shop']);
        Route::resource('/payment', 'PaymentController');
        Route::resource('/balance', 'BalanceController')->middleware(['Bank']);


        Route::get('/home', 'HomeController@index')->name('home');

        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::put('/profile', 'ProfileController@update')->name('profile.update');

        Route::put('/product', 'ProductController@index')->name('product');
        Route::put('/product-edit/{id}', 'ProductController@edit')->name('product-edit');
        Route::get('/product-destroy/{id}', 'ProductController@destroy')->name('product-destroy');

        Route::get('/payment', 'PaymentController@index')->name('payment');
        Route::get('/payment-edit', 'PaymentController@edit')->name('payment-edit');
        Route::get('/payment-destroy/{id}', 'PaymentController@destroy')->name('payment-destroy/{id}');

        Route::get('/balance', 'BalanceController@index')->name('balance');
        Route::get('/balance-edit/{id}', 'BalanceController@edit')->name('balance-edit');
        Route::get('/balance-edit/{id}', 'BalanceController@edit')->name('balance-edit');

        Route::get('/bank', 'BalanceController@index')->name('bank')->middleware('Bank');
        Route::get('/student', 'StudentController@index')->name('student')->middleware('Student');
        Route::get('/shop', 'ShopController@index')->name('shop')->middleware('Shop');

});


// Route::get('/about', function () {
//     return view('about');
// })->name('about');

// Route::get('/blank', function () {
//     return view('blank');
// })->name('blank');

// Route::middleware('auth')->group(function() {
//     Route::resource('basic', BasicController::class);
// });

resources/views/about.blade.php
@extends('layouts.admin')

@section('main-content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ __('About') }}</h1>

    <div class="row justify-content-center">

        <div class="col-lg-8">

            <div class="card shadow mb-4">

                <div class="card-profile-image mt-4">
                    <img src="{{ asset('img/favicon.png') }}" class="rounded-circle" alt="user-image">
                </div>

                <div class="card-body">

                    <div class="row">
                        <div class="col-lg-12 mb-1">
                            <div class="text-center">
                                <h5 class="font-weight-bold">Alejandro RH</h5>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4 mb-1 text-center">
                            <a href="https://facebook.com/aleckrh" target="_blank" class="btn btn-facebook btn-circle btn-lg"><i class="fab fa-facebook-f fa-fw"></i></a>
                        </div>
                        <div class="col-md-4 mb-1 text-center">
                            <a href="https://github.com/aleckrh" target="_blank" class="btn btn-github btn-circle btn-lg"><i class="fab fa-github fa-fw"></i></a>
                        </div>
                        <div class="col-md-4 mb-1 text-center">
                            <a href="https://twitter.com/aleckrh" target="_blank" class="btn btn-twitter btn-circle btn-lg"><i class="fab fa-twitter fa-fw"></i></a>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-lg-12">
                            <h5 class="font-weight-bold">Laravel SB Admin 2</h5>
                            <p>SB Admin 2 for Laravel.</p>
                            <p>Recommend to install this preset on a project that you are starting from scratch, otherwise your project's design might break.</p>
                            <a href="https://github.com/aleckrh/laravel-sb-admin-2" target="_blank" class="btn btn-github">
                                <i class="fab fa-github fa-fw"></i> Go to repository
                            </a>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-lg-12">
                            <h5 class="font-weight-bold">Credits</h5>
                            <p>Laravel SB Admin 2 uses some open-source third-party libraries/packages, many thanks to the web community.</p>
                            <ul>
                                <li><a href="https://laravel.com" target="_blank">Laravel</a> - Open source framework.</li>
                                <li><a href="https://github.com/DevMarketer/LaravelEasyNav" target="_blank">LaravelEasyNav</a> - Making managing navigation in Laravel easy.</li>
                                <li><a href="https://startbootstrap.com/themes/sb-admin-2" target="_blank">SB Admin 2</a> - Thanks to Start Bootstrap.</li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>

@endsection

resources/views/balance.blade.php
@extends('layouts.admin')

@section('main-content')

{{-- MODAL EDIT ITEM --}}
<div class="modal fade" id="modalEditItem" tabindex="-1" aria-labelledby="modalEditItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalEditItem">Top Up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="post" class="formEditItem">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group">
                        <label for="balance">Balance</label>
                        <input type="text" id="balance" name="balance" placeholder="Insert Balance" class="form-control editbalance" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-user-edit"></i></i> Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>


    <!-- Main Content goes here -->

    <div class="card">
        <div class="card-body">
            <div class="card-header mb-3">
                <h2>User Top-Up</h2>
            </div>
            <table id="example" class="table table-striped mt-4" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>User Name</th>
                        <th>Class</th>
                        <th>Balance</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach ($get_user as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->fullname }}</td>
                        <td>{{ $item->class }}</td>
                        <td> <strong>{{ number_format($item->balance) }}</strong> </td>
                        <td>
                            <button class="btn btn-sm btn-warning mr-1" data-id="{{ $item->id }}" onclick="triggerEdit({{ $item->id }})"><i class="fas fa-user-edit mr-1"></i></a></button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
      </div>

    <!-- End of Main Content -->
@endsection

@push('notif')
@if (session('success'))
<div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

@if (session('status'))
    <div class="alert alert-success border-left-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@endpush

@section('script')
<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );


    function triggerEdit(id) {
        console.log("Hai")
       $.ajax({
           url: "{{ route('balance.show','') }}/"+id,
           type: "GET",
           success: function(res){
               console.log(res)

               var elForm = document.querySelector("#modalEditItem form")
               elForm.setAttribute("action", "{{ url('balance','') }}/"+id)
               $("#modalEditItem").modal('show');
                console.log(res.project);
               $("#modalEditItem .editbalance").val(res.balance);
           },
           error: function(err){
                console.log(err)
           }
       })
    }

    $(document).ready(function() {
        console.log('tes')
        $('#triggerEdit').click(function(e) {
            console.log('s');
            let id = $(this).attr('data-id');
            console.log('a');
            console.log("{{ route('balance.show','') }}/" + id)
            $.get({
                url: "{{ route('balance.show','') }}/" + id,
                data: {
                    '_token': $('meta[name=csrf-token]').attr('content'),
                },
                success: function(res) {
                    console.log('sukses nih');
                    console.log(res);

                    $(".editbalance").val(res.balance);
                },
                error: function(err) {
                    console.log('gagal');
                    console.log(err)
                }
            })
        });
    });
</script>

@endsection

resources/views/payment.blade.php
@extends('layouts.admin')

@section('main-content')
    <!-- Page Heading -->

    {{-- modal add payment --}}
    <div class="modal fade" id="modalAddItem" tabindex="-1" aria-labelledby="modalAddItem" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalAddItem">Payment</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('payment.store') }}" method="post">
                    @csrf
            @if ($errors->any())
            <div class="alert alert-danger" role="alert">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
                    <div class="modal-body">
                        <div class="form-group" type="hidden">
                            <label for="">Items</label>
                            <select name="product_id" id="name" value="{{ old('') }}" class="form-control editItem">
                                <option selected>-- Select --</option>
                                @foreach($get_item as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="qty">Qty</label>
                            <input type="text" id="qty" name="qty" value="{{ old('') }}" placeholder="Insert Stocks" class="form-control">
                            {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalEditItem" tabindex="-1" aria-labelledby="modalEditItem" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEditItem">Edit Payment</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="post" class="formEditItem">
                    @csrf
                    @method('PUT')
                    <div class="modal-body">
                        <div class="form-group" type="hidden">
                            <label for="">Items</label>
                            <select name="product_id" id="name" value="{{ old('') }}" class="form-control editItem">
                                <option selected>-- Select --</option>
                                @foreach($get_item as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="qty">Qty</label>
                            <input type="text" id="qty" name="qty" value="{{ old('') }}" placeholder="Insert Stocks" class="form-control editqty">
                            {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Main Content goes here -->
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col">
                    <h2>Payment</h2>
                </div>
                <div class="col text-right">
                    <button type="button" href="#!" class="btn btn-primary" data-toggle="modal" data-target="#modalAddItem"><i class="fas fa-plus-circle"></i> Add Items</button>
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table id="example" class="table table-striped mt-4" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>Item Name</th>
                        <th>Qty</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    @foreach ($the_payment as $item)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->product->name }}</td>
                        <td>{{ $item->qty }}</td>
                        <td>{{ number_format($item->product->price) }}</td>
                        <td><strong> {{ number_format($item->product->price * $item->qty) }} </strong></td>
                        <td>
                            <button class="btn btn-sm btn-warning mr-1" data-id="{{ $item->id }}" onclick="triggerEdit({{ $item->id }})"><i class="fas fa-user-edit mr-1"></i></a></button>
                            <a class="btn btn-sm btn-danger ml-1" href="{{ url('/payment-destroy', $item->id) }}" role="button"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


    <!-- End of Main Content -->
@endsection

@push('notif')
@if (session('success'))
<div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

@if (session('status'))
    <div class="alert alert-success border-left-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@endpush

<script>
    $(document).ready(function() {
    $('#example').DataTable();
    } );

    function triggerEdit(id) {
        console.log("Hai")
    $.ajax({
        url: "{{ route('payment.show','') }}/"+id,
        type: "GET",
        success: function(res){
            console.log(res)

            var elForm = document.querySelector("#modalEditItem form")
            elForm.setAttribute("action", "{{ url('payment','') }}/"+id)
            $("#modalEditItem").modal('show');
                console.log(res.project);
            $("#modalEditItem .edititem").val(res.product_id);
            $("#modalEditItem .editqty").val(res.qty);
        },
        error: function(err){
                console.log(err)
        }
    })
    }

    $(document).ready(function() {
        console.log('tes')
        $('#triggerEdit').click(function(e) {
            console.log('s');
            let id = $(this).attr('data-id');
            console.log('a');
            console.log("{{ route('payment.show','') }}/" + id)
            $.get({
                url: "{{ route('payment.show','') }}/" + id,
                data: {
                    '_token': $('meta[name=csrf-token]').attr('content'),
                },
                success: function(res) {
                    console.log('sukses nih');
                    console.log(res);

                    $(".edititem").val(res.product_id);
                    $(".editqty").val(res.qty);
                },
                error: function(err) {
                    console.log('gagal');
                    console.log(err)
                }
            })
        });
    });

</script>

resources/views/product.blade.php
@extends('layouts.admin')

@section('main-content')

{{-- MODAL ADD ITEM --}}
<div class="modal fade" id="modalAddItem" tabindex="-1" aria-labelledby="modalAddItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalAddItem">Add New Items</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('product.store') }}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Item Name</label>
                        <input type="text" id="name" name="name" value="{{ old('') }}" placeholder="Insert Item Name" class="form-control">
                        {{-- @error('nama_barang') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="stocks">Stocks</label>
                        <input type="number" id="stocks" name="stocks" value="{{ old('') }}" placeholder="Insert Stocks" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="number" id="price" name="price" value="{{ old('') }}" placeholder="Insert Price" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- MODAL EDIT ITEM --}}
<div class="modal fade" id="modalEditItem" tabindex="-1" aria-labelledby="modalEditItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalEditItem">Add New Items</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="post" class="formEditItem">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Item Name</label>
                        <input type="text" id="name" name="name" placeholder="Insert Item Name" class="form-control editname">
                        {{-- @error('nama_barang') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="stocks">Stocks</label>
                        <input type="number" id="stocks" name="stocks" placeholder="Insert Stocks" class="form-control editstocks">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="number" id="price" name="price" placeholder="Insert Price" class="form-control editprice">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                </div>
            </form>
        </div>
    </div>
</div>


    <!-- Main Content goes here -->

    <div class="card">
        <div class="card-body">
            <div class="card-header mb-3">
                <div class="row">
                    <div class="col">
                        <h2>Products List</h2>
                    </div>
                    <div class="col text-right">
                        <button type="button" href="#!" class="btn btn-primary" data-toggle="modal" data-target="#modalAddItem"><i class="fas fa-plus-circle"></i> Add Items</button>
                        </button>
                    </div>
                </div>
            </div>
            <table id="example" class="table table-striped mt-4" style="width:100%">
                <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th>Item Name</th>
                        <th>Qty</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($product as $item)
                        <tr class="text-center">
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->stocks }}</td>
                            <td>{{ number_format($item->price) }}</td>
                            <td>
                                <button class="btn btn-sm btn-warning mr-1" data-id="{{ $item->id }}" onclick="triggerEdit({{ $item->id }})"><i class="fas fa-user-edit mr-1"></i></a></button>
                                <a class="btn btn-sm btn-danger ml-1" href="{{ url('/product-destroy', $item->id) }}" role="button"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
      </div>

    <!-- End of Main Content -->
@endsection

@push('notif')
@if (session('success'))
<div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

@if (session('status'))
    <div class="alert alert-success border-left-success" role="alert">
        {{ session('status') }}
    </div>
@endif
@endpush

@section('script')
    <script>
        $(document).ready(function() {
        $('#example').DataTable();
        } );

        function triggerEdit(id) {
            console.log("Hai")
        $.ajax({
            url: "{{ route('product.show','') }}/"+id,
            type: "GET",
            success: function(res){
                console.log(res)

                var elForm = document.querySelector("#modalEditItem form")
                elForm.setAttribute("action", "{{ url('product','') }}/"+id)
                $("#modalEditItem").modal('show');
                    console.log(res.project);
                $("#modalEditItem .editname").val(res.name);
                $("#modalEditItem .editstocks").val(res.stocks);
                $("#modalEditItem .editprice").val(res.price);
            },
            error: function(err){
                    console.log(err)
            }
        })
        }

        $(document).ready(function() {
            console.log('tes')
            $('#triggerEdit').click(function(e) {
                console.log('s');
                let id = $(this).attr('data-id');
                console.log('a');
                console.log("{{ route('product.show','') }}/" + id)
                $.get({
                    url: "{{ route('product.show','') }}/" + id,
                    data: {
                        '_token': $('meta[name=csrf-token]').attr('content'),
                    },
                    success: function(res) {
                        console.log('sukses nih');
                        console.log(res);

                        $(".editname").val(res.name);
                        $(".editstocks").val(res.stocks);
                        $(".editprice").val(res.price);
                    },
                    error: function(err) {
                        console.log('gagal');
                        console.log(err)
                    }
                })
            });
        });

    </script>

@endsection